// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package Catan_Part3;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

/**
 * Represents a player (Agent) in the Catan game.
 * Handles building roads, settlements, and cities.
 * handle the resources card that the agent has
 *
 * @author Zain Khalboos
 * Course: SFWRENG 2AA4
 * Date: 2026-02-13add
 */
public class ComputerAgent extends Agent {

    private int edgeId;
    private int nodeId;
    private final Random random = new Random();
    private ConstraintHandler chain;

    /**
     * Constructor for agent
     *
     * @param id
     * @param resources
     * @param points
     */
    public ComputerAgent(int id, Resources resources, int points, Agent[] allAgents) {

        super(id, resources, points);

        OverSevenCardsHandler h1 = new OverSevenCardsHandler();
        ConnectRoadSegmentsHandler h2 = new ConnectRoadSegmentsHandler();
        LongestRoadHandler h3 = new LongestRoadHandler(allAgents);

        h1.setSuccessor(h2);
        h2.setSuccessor(h3);
        chain = h1;
    }

    public int getEdgeId() {
        return edgeId;
    }

    public int getNodeId() {
        return nodeId;
    }


    @Override
    public void takeTurn(GameMap map, int round, int rollDice) {

        boolean handled = chain.handle(this, map, round);

        if (!handled) {

        }

    }


    /**
     * we try to build if we build we subtract 1 from roadsRemaining
     * @param map
     * @return boolean
     * **/
    @Override
    protected boolean tryBuildRoad(GameMap map) {
        if (roadsRemaining <= 0) return false;
        if(!checkRoadCost()){return false;}

        edgeId=roadLocation(map);
        if(edgeId==-1){return false;}

        if(map.placeRoad(this, edgeId)){
            buyRoad();
            roadsRemaining--;
            return true;
        }

        return false;
    }

    /**
     * we try to build if we build we subtract 1 from settlementRemaining
     * @param map
     * @return boolean
     * **/
    //MAKE ABSTRACT METHOD INSETAD
    @Override
    protected boolean tryBuildSettlement(GameMap map){
        if (settlementsRemaining <= 0) return false;
        if(!checkSettlementCost()){return false;}

        nodeId=settlementLocation(map, false);
        if(nodeId==-1){return false;}

        if(map.placeSettlement(this, nodeId, false)){
            buySettlement();
            settlementsRemaining--;
            return true;
        }

        return false;
    }

    /**
     * we try to build if we build we subtract 1 from cityRemaining
     * @param map
     * @return boolean
     * **/
    @Override
    protected boolean tryBuildCity(GameMap map){
        if (citiesRemaining <= 0) return false;
        if(!checkCityCost()){return false;}

        nodeId=cityLocation(map);
        if (nodeId == -1) return false;

        if(map.isSettlement(this, nodeId) && checkCityCost()){
            map.upgrade(this, nodeId);
            buyCity();
            citiesRemaining--;
            settlementsRemaining++;
            return true;
        }

        return false;
    }

    @Override
    public void initialTurn(GameMap map, boolean distributeResources) {
        int nodeId = settlementLocation(map, true);
        map.placeSettlement(this, nodeId, true);
        if (distributeResources) map.distributeInitialResources(this, nodeId);
        int edgeId = roadLocation(map);
        map.placeRoad(this, edgeId);
    }
}
