// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part3;

/**
 * Represents the Catan game board and its relationships (tiles, nodes, edges).
 * Provides utilities for board initialization and placement/validation logic.
 *
 * @author Zain Al-Sakaji
 * @author  Harnoor Sagar
 * @version 1.0.0
 */

import java.util.*;


public class GameMap {


    private ArrayList<Tile> tiles;
    private ArrayList<Node> nodes;
    private ArrayList<Edge> edges;

    private Map<Integer, List<Integer>> tilesToNodes;
    private Map<Integer, List<Integer>> edgeToNodes;
    private Map<Integer, List<Integer>> nodeNeighbors;



     //Initializes collections for tiles, nodes, edges, and their relationship maps.
     
    public  GameMap() {
        tiles= new ArrayList<Tile>();
        nodes=new ArrayList<Node>();
        edges=new ArrayList<Edge>();

        tilesToNodes= new HashMap<Integer, List<Integer>>();
        edgeToNodes = new HashMap<Integer, List<Integer>>();
        nodeNeighbors= new HashMap<Integer, List<Integer>>();

    }

// Builds the board by creating tiles/nodes/edges and wiring all adjacency mappings.
    public void initboard(){

        //initialize all nodes, tiles and edges
        initEdge();
        initNode();
        initTiles();
        initMaps();


        //initialize all relationship between nodes, tiles and edges
        initNodeToNode();
        initEdgeToNodes();
        initTilesToNodes();

    }





    /*A list of helper functions to aid with initializing the board and establishing relationship between tiles, nodes and edges* */


    //HELPERS FOR INITIALIZE THE BOARD

    //init all 19 tiles
    private void initTiles(){
        //center Tile (0)
        tiles.add(new Tile(0, ResourceType.WOOD, 10));
        //inner ring (1-6)
        tiles.add(new Tile(1, ResourceType.WHEAT, 11));
        tiles.add(new Tile(2, ResourceType.BRICK, 8));
        tiles.add(new Tile(3, ResourceType.ORE, 3));
        tiles.add(new Tile(4, ResourceType.SHEEP, 11));
        tiles.add(new Tile(5, ResourceType.SHEEP, 5));
        tiles.add(new Tile(6, ResourceType.SHEEP, 12));
        //outer ring (7-18)
        tiles.add(new Tile(7, ResourceType.WHEAT, 3));
        tiles.add(new Tile(8, ResourceType.ORE, 6));
        tiles.add(new Tile(9, ResourceType.WOOD, 4));
        tiles.add(new Tile(10, ResourceType.ORE, 6));
        tiles.add(new Tile(11, ResourceType.WHEAT, 9));
        tiles.add(new Tile(12, ResourceType.WOOD, 5));
        tiles.add(new Tile(13, ResourceType.BRICK, 9));
        tiles.add(new Tile(14, ResourceType.BRICK, 8));
        tiles.add(new Tile(15, ResourceType.WHEAT, 4));
        tiles.add(new Tile(16, ResourceType.DESERT, -1)); // -1 indicated it has no token (empty)
        tiles.add(new Tile(17, ResourceType.WOOD, 2));
        tiles.add(new Tile(18, ResourceType.SHEEP, 10));
    }

//init all 54 nodes
    private void initNode(){
        //create 54 nodes (establish relationship later)
        for (int i=0; i<54; i++){
            nodes.add(new Node(i));
        }
    }
//Init 72 edges
    private void initEdge(){
        //create 72 unique edges
        for (int i=0; i<72; i++){
            edges.add(new Edge(i));
        }
    }

    //init the lists in the hash maps
    //maps just store ids not the full object
    private void initMaps(){
        for (int i=0; i<tiles.size(); i++){
            tilesToNodes.put(i, new ArrayList<Integer>());
        }

        for (int i=0; i<edges.size();i++){
            edgeToNodes.put(i, new ArrayList<Integer>());
        }
        for (int i = 0; i < nodes.size(); i++) {
            nodeNeighbors.put(i, new ArrayList<Integer>());

        }
    }


    //HELPERS for establishing relationship b/n nodes, tiles and edges

    // helper method to allow nodes to recognize  who their neighbors are
    private void addSingleNodeNeighbor(int nodeId1, int nodeId2){
        //do nothing if the nodes do not exist
        if (getNode(nodeId1)==null || getNode(nodeId2)==null){
            return;
        }
        //add node 2 as a neighbor for node 1
        if (!nodeNeighbors.get(nodeId1).contains(nodeId2)){
            nodeNeighbors.get(nodeId1).add(nodeId2);
        }
        //other way around
        if (!nodeNeighbors.get(nodeId2).contains(nodeId1)){
            nodeNeighbors.get(nodeId2).add(nodeId1);
        }

    }

    //takes in a node, and any number of surrounding nodes to establish a
    //neighbor relationship for all of them
    private void addAllNeighbors(int node, int... neighbors){
        //adds every neighbor node with the original
        for (int n: neighbors){
            addSingleNodeNeighbor(node, n);
        }
    }
    //hard coding node to node relationships
    private void initNodeToNode(){
        //top Row
        addAllNeighbors(40, 42, 41);
        addAllNeighbors(43, 41, 44);
        addAllNeighbors(45, 44, 46);

        //upper middle row
        addAllNeighbors(42, 40, 38);
        addAllNeighbors(41, 40, 43, 16);
        addAllNeighbors(44, 19, 43, 45);
        addAllNeighbors(46, 47, 45);

        //middle row
        addAllNeighbors(38, 42, 39, 18);
        addAllNeighbors(16, 41, 17, 18);
        addAllNeighbors(19, 44, 20, 17);
        addAllNeighbors(47, 46, 48, 20);

        //center Upper row
        addAllNeighbors(39, 38, 35);
        addAllNeighbors(18, 38, 16, 13);
        addAllNeighbors(17, 0, 16, 19);
        addAllNeighbors(20, 21, 19, 47);
        addAllNeighbors(48, 49, 47);

        //center row
        addAllNeighbors(35, 39, 37, 15);
        addAllNeighbors(13, 18, 5, 15);
        addAllNeighbors(0, 5, 17, 1);
        addAllNeighbors(21, 20, 22, 1);
        addAllNeighbors(49, 48, 50, 22);

        //center lower row
        addAllNeighbors(37, 36, 35);
        addAllNeighbors(15, 35, 13, 14);
        addAllNeighbors(5, 13, 0, 4);
        addAllNeighbors(1, 0, 21, 2);
        addAllNeighbors(22, 21, 49, 23);
        addAllNeighbors(50, 49, 51);

        //lower middle row
        addAllNeighbors(36, 37, 34);
        addAllNeighbors(14, 15, 12, 34);
        addAllNeighbors(4, 5, 3, 12);
        addAllNeighbors(2, 1, 6, 3);
        addAllNeighbors(23, 22, 52, 6);
        addAllNeighbors(51, 50, 52);

        //lower row
        addAllNeighbors(34, 36, 33);
        addAllNeighbors(12, 14, 4, 11);
        addAllNeighbors(3, 4, 2, 9);
        addAllNeighbors(6, 2, 23, 7);
        addAllNeighbors(52, 23, 51, 53);

        //bottom
        addAllNeighbors(33, 34, 32);
        addAllNeighbors(11, 12, 10, 32);
        addAllNeighbors(9, 3, 8, 10);
        addAllNeighbors(7, 6, 24, 8);
        addAllNeighbors(53, 52, 24);

        //bottom even more
        addAllNeighbors(32, 33, 11, 31);
        addAllNeighbors(10, 11, 9, 29);
        addAllNeighbors(8, 9, 7, 27);
        addAllNeighbors(24, 7, 53, 25);

        //tips
        addAllNeighbors(31, 32, 30);
        addAllNeighbors(29, 10, 28, 30);
        addAllNeighbors(27, 8, 26, 28);
        addAllNeighbors(25, 24, 26);
        addAllNeighbors(30, 21, 29);
        addAllNeighbors(28, 29, 27);
        addAllNeighbors(26, 27, 25);
    }

    //helper methods for a relationship between  every edge and two nodes
    private void addEdgeBetweenNodes(int edge, int node1, int node2){
        if (edges.get(edge)==null || nodes.get(node1)==null || nodes.get(node2)==null){
            return;
        }
        edgeToNodes.get(edge).add(node1);
        edgeToNodes.get(edge).add(node2);

    }

    //hard coding relationship between each edge and its own node
    private void initEdgeToNodes(){
        // (0-9)
        addEdgeBetweenNodes(0, 42, 40);
        addEdgeBetweenNodes(1, 40, 41);
        addEdgeBetweenNodes(2, 41, 43);
        addEdgeBetweenNodes(3, 43, 44);
        addEdgeBetweenNodes(4, 44, 45);
        addEdgeBetweenNodes(5, 45, 46);
        addEdgeBetweenNodes(6, 38, 42);
        addEdgeBetweenNodes(7, 16, 41);
        addEdgeBetweenNodes(8, 19, 44);
        addEdgeBetweenNodes(9, 47, 46);

        // (10-14)
        addEdgeBetweenNodes(10, 39, 38);
        addEdgeBetweenNodes(11, 38, 18);
        addEdgeBetweenNodes(12, 18, 16);
        addEdgeBetweenNodes(13, 16, 17);
        addEdgeBetweenNodes(14, 17, 19);

        //  (15-19)
        addEdgeBetweenNodes(15, 19, 20);
        addEdgeBetweenNodes(16, 28, 47);
        addEdgeBetweenNodes(17, 47, 48);
        addEdgeBetweenNodes(18, 35, 39);
        addEdgeBetweenNodes(19, 13, 18);

        // Center (20-25)
        addEdgeBetweenNodes(20, 0, 17);
        addEdgeBetweenNodes(21, 21, 20);
        addEdgeBetweenNodes(22, 49, 48);
        addEdgeBetweenNodes(23, 37, 35);
        addEdgeBetweenNodes(24, 35, 15);
        addEdgeBetweenNodes(25, 15, 13);

        // Center lower (26-31)
        addEdgeBetweenNodes(26, 13, 5);
        addEdgeBetweenNodes(27, 5, 0);
        addEdgeBetweenNodes(28, 0, 1);
        addEdgeBetweenNodes(29, 1, 21);
        addEdgeBetweenNodes(30, 21, 22);
        addEdgeBetweenNodes(31, 22, 49);

        // Lower middle (32-37)
        addEdgeBetweenNodes(32, 49, 50);
        addEdgeBetweenNodes(33, 36, 37);
        addEdgeBetweenNodes(34, 14, 15);
        addEdgeBetweenNodes(35, 4, 5);
        addEdgeBetweenNodes(36, 2, 1);
        addEdgeBetweenNodes(37, 23, 22);

        // Lower (38-42)
        addEdgeBetweenNodes(38, 51, 50);
        addEdgeBetweenNodes(39, 36, 34);
        addEdgeBetweenNodes(40, 34, 14);
        addEdgeBetweenNodes(41, 14, 12);
        addEdgeBetweenNodes(42, 12, 4);

        // Bottom (43-47)
        addEdgeBetweenNodes(43, 4, 3);
        addEdgeBetweenNodes(44, 3, 2);
        addEdgeBetweenNodes(45, 2, 6);
        addEdgeBetweenNodes(46, 6, 23);
        addEdgeBetweenNodes(47, 23, 52);

        // Bottom-most (48-51)
        addEdgeBetweenNodes(48, 52, 51);
        addEdgeBetweenNodes(49, 33, 34);
        addEdgeBetweenNodes(50, 11, 12);
        addEdgeBetweenNodes(51, 9, 5);

        // Bottom tips (52-54)
        addEdgeBetweenNodes(52, 7, 6);
        addEdgeBetweenNodes(53, 53, 52);
        addEdgeBetweenNodes(54, 33, 32);

        // Remaining edges to complete 72 (55-71)
        addEdgeBetweenNodes(55, 32, 11);
        addEdgeBetweenNodes(56, 11, 10);
        addEdgeBetweenNodes(57, 10, 9);
        addEdgeBetweenNodes(58, 9, 8);
        addEdgeBetweenNodes(59, 8, 7);
        addEdgeBetweenNodes(60, 7, 24);
        addEdgeBetweenNodes(61, 24, 53);
        addEdgeBetweenNodes(62, 31, 32);
        addEdgeBetweenNodes(63, 29, 10);
        addEdgeBetweenNodes(64, 27, 8);
        addEdgeBetweenNodes(65, 25, 24);
        addEdgeBetweenNodes(66, 31, 30);
        addEdgeBetweenNodes(67, 30, 29);
        addEdgeBetweenNodes(68, 29, 28);
        addEdgeBetweenNodes(69, 28, 27);
        addEdgeBetweenNodes(70, 27, 26);
        addEdgeBetweenNodes(71, 26, 25);
    }

    //helper methods for tiles with nodes
    private void addTileToNodes(int tileId, int... nodeIds){
        if (tiles.get(tileId)==null){return ;}

        for (int node: nodeIds){
            if (nodes.get(node) != null){
                tilesToNodes.get(tileId).add(node);
            }
        }
    }

    //hard coding which nodes go with which tiles

    private void initTilesToNodes(){

        addTileToNodes(0, 0, 1, 2, 3, 4, 5); // center

        // inner ring ( 1-6)
        addTileToNodes(1, 2, 6, 7, 8, 9, 3);  // Bottom-right inner
        addTileToNodes(2, 4, 3, 9, 10, 11, 12);  // Bottom-left inner
        addTileToNodes(3, 13, 5, 4, 12, 14, 15);        // Middle-left inner
        addTileToNodes(4, 16, 17, 0, 5, 13, 18);    // Top-left inner
        addTileToNodes(5, 19, 20, 21, 1, 0, 17);     // Top-right inner
        addTileToNodes(6, 21, 22, 23, 6, 2, 1);  // Middle-right inner

        // Outer ring ( 7-18)
        addTileToNodes(7, 7, 24, 25, 26, 27, 8);  // Bottom-right outer
        addTileToNodes(8, 9, 8, 27, 28, 29, 10);  // Bottom-middle outer
        addTileToNodes(9, 11, 10, 29, 30, 31, 32);  // Bottom-left outer
        addTileToNodes(10, 14, 12, 11, 32, 33, 34); // Left-diagonal-bottom outer
        addTileToNodes(11, 35, 15, 14, 34, 36, 37); // Left-middle outer
        addTileToNodes(12, 38, 18, 13, 15, 35, 39); // Left-diagonal-top outer
        addTileToNodes(13, 40, 42, 16, 18, 38, 42); // Top-left outer
        addTileToNodes(14, 43, 44, 19, 17, 16, 41); // Top-middle outer
        addTileToNodes(15, 45, 46, 47, 20, 19, 44); // Top-right outer
        addTileToNodes(16, 47, 48, 49, 22, 21, 20); // Right-diagonal-top outer
        addTileToNodes(17, 49, 50, 51, 52, 23, 22); // Right-middle outer
        addTileToNodes(18, 23, 52, 53, 24, 7, 6); // Right-diagonal-bottom outer

    }


    //creates and returns a list of all the neigbors of a node
    private List<Integer> getNeighborNodes(int nodeId){
        return nodeNeighbors.getOrDefault(nodeId, new ArrayList<>());
    }

    public boolean isValidSettlementPosition(int nodeId){
        boolean valid = true;
        Node targetNode= getNode(nodeId);
        //check if the node does not exist
        if (targetNode==null)
            return false;

        //Check if node is full
        if (targetNode.getBuilding()!=null)
            return false;


        //check that no neigbor of the node is full (has a building etc)
        for (int neighborId: getNeighborNodes(nodeId)){
            //get that specfic node object
            Node neighbor=getNode(neighborId);
            //check if its a valid node and is not full
            if (neighbor!= null && neighbor.isOccupied()){ valid = false;}
        }




//if it does not violate any rules we return true to indicate that the node is a valid position place
        return valid;
    }
//does this agent have atleast one road touching this node
    //if they do then they are allowed to build here
    //id not they cant build there
    public boolean hasAdjacentRoad(Agent agent, int nodeId) {

        //check if the agent does in fact exist
        if (agent == null)
            return false;

        //look at every edge
        for (int edgeId : edgeToNodes.keySet()) {

            //find the  nodes that are associated with this edge
            List<Integer> nodes = edgeToNodes.get(edgeId);

            //check if that edge touches our node
            if (nodes.contains(nodeId)) {
                Edge edge = edges.get(edgeId);
                if (edge == null) continue;

                //if the edge touches our node, it must have a road and that road must belong to this agent
                if (edge.getRoad() != null && agent.equals(edge.getRoad().getOwner())) {
                    return true; //FOUND one adjacent road owned by the agent
                }


            }
        }
        return false;
    }


    
    
    //helper method returns a list of which edges are touching this node
    //check if the agent has a road, sett, city at either end of the edge
    public boolean isConnectedToAgent(Agent agent, int edgeId){

        //stores both end points of the edge
        List<Integer> endpoints= edgeToNodes.get(edgeId);

        for (int nodeId: endpoints) {
            //check if the nodes have a building (either settlement or city)
            Node node = getNode(nodeId);
            if (node != null && node.isOccupied() && agent.equals(node.getBuilding().getOwner())) {
                return true;
            }
            //check for any road on any other edge at this node
            if (hasAdjacentRoad(agent,nodeId)){
                return true;
            }

        }
        return false;

    }







    public Tile getTile(int id) {
        if (id>=0 && id<tiles.size()){
            return tiles.get(id);
        }
        return null;
	}

	/**
	 * 
	 * @param id 
	 * @return node
	 */
	public Node getNode(int id) {

        if (id>=0 && id<nodes.size()){
            return nodes.get(id);
        }
        return null;

    }

	/**
	 * 
	 * @param id 
	 * @return  edge
	 */
	public Edge getEdge(int id) {
        //check if the id does truly exist and that it is not out of bounds
        if (id>=0){
            return edges.get(id);

        }
        return null;
    }





    /**
     *
     * Checks if the road on a specific edge is owned by the agent
     *
     */
    public boolean isRoad(Agent agent, int edgeId) {
        Edge edge = getEdge(edgeId);

        // if edge exists and is occupied,
        // return whether this agent is the owner
        if (edge != null && edge.isOccupied()) {
            return edge.getRoad().getOwner() == agent;
        }

        return false;
    }

    /**
     *
     * Checks if settlement on the specific node is owned by the agent
     *
     */
    public boolean isSettlement(Agent agent, int nodeId) {
        Node node = getNode(nodeId);

        // if the node exists and is occupied and the building on the node is a settlement,
        // return whether this agent is the owner
        if (node != null && node.isOccupied() && node.getBuilding() instanceof Settlement) {
            return node.getBuilding().getOwner() == agent;
        }

        return false;
    }

    /**
     *
     * Checks if the city on the specific node is owned by the agent
     */
    public boolean isCity(Agent agent, int nodeId) {
        Node node = getNode(nodeId);

        // if the node exists and is occupied and the building on the node is a city,
        // return whether this agent is the owner
        if (node != null && node.isOccupied() && node.getBuilding() instanceof City) {
            return node.getBuilding().getOwner() == agent;
        }

        return false;
    }

    /**
     *
     * Places the road on the specific edge for the agent
     *
     * - Checks if the edge already has a road on it
     * - checks if the edge getting the road is connected to an existing road
     *   settlement or city owned by the same agent
     *
     */
    public boolean placeRoad(Agent agent, int edgeId) {
        Edge edge = getEdge(edgeId);

        // returns false if edge is null or already occupied
        if (edge == null || edge.isOccupied()) {
            return false;
        }

        // return false if edge is connected to an existing agent building or road
        if (!isConnectedToAgent(agent, edgeId)) {
            return false;
        }

        // creates new road and sets it on that edge
        edge.setRoad(new Road(agent, edgeId));

        // adds road points to agent when road is placed
        agent.addPoints(edge.getRoad().getPoints());
        return true;
    }





    /**
     *
     * places a settlement on the specific node for the agent
     *
     *  - Settlements must follow distance rule (no neighboring node must have settlement or city)
     *  - must connect to one of the agent owned roads (skipped during initial placement)
     */
    public boolean placeSettlement(Agent agent, int nodeId, boolean isInitialPlacement) {
        Node node = getNode(nodeId);

        if(nodeId < 0){
            return false;
        }

        // return false if the node doesn't exist or is occupied
        if (node == null || node.isOccupied()) {
            return false;
        }

        // returns false if neighbouring node has a settlement
        if (!isValidSettlementPosition(nodeId)){
              return false;
        }

        // checks if it is the first placements and
        // whether the node is attached to a road
        if (!isInitialPlacement && !hasAdjacentRoad(agent, nodeId)) {
              return false;
        }

        // creates a settlement and sets building
        node.setBuilding(new Settlement(agent, nodeId));

        // adds settlement points to agent
        agent.addPoints(node.getBuilding().getPoints());
        return true;

    }

    /**
     * Places a city on the specified node by upgrading an existing agent settlement
     *
     * - settlement must be owned by same agent
     *
     */
    private boolean placeCity(Agent agent, int nodeId) {
        Node node = getNode(nodeId);

        // checks if node exists
        if (node == null) {
            return false;
        }

        // checks if node has a settlement by the agent
        if (!isSettlement(agent, nodeId)) {
            return false;
        }

        // swithces settlement to a city
        node.setBuilding(new City(agent, nodeId));

        // adds city points to agent
        agent.addPoints(node.getBuilding().getPoints());
        return true;
    }

    /**
     * public wrapper for placeCity.
     *
     * upgrades existing settlement to a city
     */
    public boolean upgrade(Agent agent, int nodeId) {
        return placeCity(agent, nodeId);
    }

    /**
     *
     * distributes the initial resources to an agent based on the location of their second settlement
     *
     * agent receives one resource card from each of the 3 adjacent tiles
     *
     */
    public void distributeInitialResources(Agent agent, int settlementNodeId) {

        // loop through all tiles and check if this node touches that tile
        for (Tile tile : tiles) {

            if (tile.getResourceType() == ResourceType.DESERT) {
                continue;
            }

            // get the list of node ids related to this tile
            List<Integer> adjacentNodes = tilesToNodes.get(tile.getId());
            if (adjacentNodes == null) continue;

            // if this settlement's node is on that tile, get resource
            if (adjacentNodes.contains(settlementNodeId)) {
                // setup rule = 1 card per adjacent tile
                agent.getResources().add(tile.getResourceType(), 1);
            }
        }
    }


    /**
     * distributes resources to the agents based on the dice roll
     *
     * if the tile token matches the roll amount, the agents receive 1 or 2
     * resources based on if they have a settlement or city there
     * if a 7 is rolled, no resources are distributed (robber is ignored)
     */
    public void distributeResources(int diceRoll) {

        Robber robber = new Robber();

        if (diceRoll == 7) {
            System.out.println("No resources distributed (rolled a 7)");
            return;
        }

        for (Tile tile : tiles) {

            // skips if desert
            if (tile.getResourceType() == ResourceType.DESERT) {
                continue;
            }

            // doesn't distribute resources if robber is on that tile
            if (tile.getId() == robber.getTileId()) {
                continue;
            }

            // skips if token num doesnt match dice roll
            if (tile.getNumberToken() != diceRoll) {
                continue;
            }

            // gets all nodes around this tile
            List<Integer> adjacentNodes = tilesToNodes.get(tile.getId());

            // checks each node for buildings
            for (int nodeId : adjacentNodes) {

                Node node = getNode(nodeId);

                // skip if node doesnt exist or is unoccupied
                if (node == null || !node.isOccupied()) {
                    continue;
                }

                // gets the owner, the building and resource amount allotted to it
                Building building = node.getBuilding();
                int resourceAmount = building.getResourceAmount();
                Agent owner = building.getOwner();

                // gives the owner the amount of resources allotted of the tile resource type
                owner.getResources().add(tile.getResourceType(), resourceAmount);
            }


        }

        
    }

    // moves the robber to a random tile when a 7 is rolled
    public void moveRobberRandom(Robber robber) {

        Random rand = new Random();
        int newTile;

        do {
            newTile = rand.nextInt(tiles.size());
        } while (newTile == robber.getTileId());

        robber.setTileId(newTile);
        System.out.println("\nPlaced robber at tile " + robber.getTileId());
    }

    // gets the list of agents who have a settlement or city on the nodes adjacent to the tile the robber is on
    public List<Agent> robberTileAdjacent (Agent agentRolled, int tileId) {

        List<Agent> choices = new ArrayList<>();

        // gets adjacent nodes from tiles to nodes
        List<Integer> adjacentNodes = tilesToNodes.get(tileId);

        for (int id : adjacentNodes){

            Node node = getNode(id);

            // if the node has a settlement or a city, get the owner, and add to list
            if (node != null && node.isOccupied()) {
                Agent owner = node.getBuilding().getOwner();

                if (owner != agentRolled && !choices.contains(owner)) {
                    choices.add(owner);
                }
            }
        }
        System.out.println("Adjacent player choices: ");

        if (choices.isEmpty()) {
            System.out.println("none");
        }
        for (int i =  0; i < choices.size(); i++) {
            System.out.println(choices.get(i).getId());
        }

        return choices;

    }

    public List<Integer> getEdgeNodes(int edgeId) {
        return edgeToNodes.get(edgeId);
    }
//given two nodes, it will return the edge connecting them
    public int getEdgeIdFromTwoNodes(int nodeA, int nodeB){
        for (Map.Entry<Integer, List<Integer>> entry: edgeToNodes.entrySet()){
            int edgeId=entry.getKey();
            List<Integer> endpoints=entry.getValue();

            if (endpoints.contains(nodeA) && endpoints.contains(nodeB)) return edgeId;
        }
        return -1;//no edge exists between those two nodes
    }

    protected void removeSettlement(HumanAgent humanAgent, int nodeId) {
        Node node = getNode(nodeId);

        humanAgent.addPoints(-node.getBuilding().getPoints()); //remove added points
        node.setBuilding(null);
    }

    protected void removeCity(HumanAgent humanAgent, int nodeId) {
        Node node = getNode(nodeId);

        humanAgent.addPoints(-node.getBuilding().getPoints()); //remove added points
        node.setBuilding(new Settlement(humanAgent, nodeId));
    }

    protected void removeRoad(HumanAgent humanAgent, int fromNodeId, int toNodeId) {
        int edgeId = getEdgeIdFromTwoNodes(fromNodeId,toNodeId);

        Edge edge = getEdge(edgeId);

        humanAgent.addPoints(-edge.getRoad().getPoints()); //remove the added points
        edge.setRoad(null); //remove the road
    }

}
