// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package Catan_Part2;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

/**
 * Represents a player (Agent) in the Catan game.
 * Handles building roads, settlements, and cities.
 * handle the resources card that the agent has
 *
 * @author Zain Khalboos
 * Course: SFWRENG 2AA4
 * Date: 2026-02-13add
 */
public abstract class Agent {

    private int id;

    private int totalPoints;
    /**
     *
     */
    private Resources resources;
    protected int roadsRemaining;
    protected int settlementsRemaining;
    protected int citiesRemaining;



    private final Random random = new Random();
    /**
     *Constructor for agent
     * @param id
     * @param resources
     * @param points
     */
    public Agent(int id, Resources resources, int points) {
        this.id = id;
        this.resources = resources;
        this.totalPoints = points;
        roadsRemaining = 15; //number of roads agent has
        settlementsRemaining = 5; //number of roads agent has
        citiesRemaining = 4;//number of roads agent has
    }

    /**
     * get the resources that player has
     * @return Resourses
    * */
    public Resources getResources() {
        return resources;
    }

    /**
     *get the id of the player
     * @return int
     */
    public int getId() {
        return id;
    }


    /**
     * Let the player take turn throw random building they can do with their resources
     * @param round
     * @param map
     * retun
     */
    public abstract void takeTurn(GameMap map, int round, int rollDice);

    /**
     * we try to build if we build we subtract 1 from roadsRemaining
     * @param map
     * @return boolean
     * **/
    protected abstract boolean tryBuildRoad(GameMap map);

    /**
     * we try to build if we build we subtract 1 from settlementRemaining
     * @param map
     * @return boolean
     * **/

    //MAKE ABSTRACT METHOD INSETAD
    protected abstract boolean tryBuildSettlement(GameMap map);

    /**
     * we try to build if we build we subtract 1 from cityRemaining
     * @param map
     * @return boolean
     * **/
    protected abstract boolean tryBuildCity(GameMap map);

    /**
     *
     * get total points player has
     * @return int
     *
     * **/
    public int getTotalPoints() {
        return totalPoints;
    }

    /**
     *takes the resources from the resources list for road
     * @return boolean
     */
    public void buyRoad() {
        resources.remove(ResourceType.WOOD, 1);
        resources.remove(ResourceType.BRICK, 1);
    }


    /**
     *
     * check if we have the cost for road
     * @return boolean
    * **/
    public boolean checkRoadCost() {
        return (resources.hasResource(ResourceType.WOOD, 1) && resources.hasResource(ResourceType.BRICK, 1));
    }

    /**
     *takes the resources from the resources list for Settlement
     * @return boolean
     */
    public void buySettlement() {
        // Cost: 1 wood, 1 brick, 1 wheat, 1 sheep
        resources.remove(ResourceType.WOOD, 1);
        resources.remove(ResourceType.BRICK, 1);
        resources.remove(ResourceType.WHEAT, 1);
        resources.remove(ResourceType.SHEEP, 1);

    }


    /**
     *
     * check if we have the cost for settlement
     * @return boolean
     * **/
    public boolean checkSettlementCost() {
        return (resources.hasResource(ResourceType.WOOD, 1)
                && resources.hasResource(ResourceType.BRICK, 1)
                && resources.hasResource(ResourceType.WHEAT, 1)
                && resources.hasResource(ResourceType.SHEEP, 1));
    }

    /**
     *takes the resources from the resources list for City
     * @return boolean
     */
    public void buyCity() {
        // Cost: 2 wheat, 3 ore
        resources.remove(ResourceType.WHEAT, 2);
        resources.remove(ResourceType.ORE, 3);
    }

    /**
     *
     * check if we have the cost for city
     * @return boolean
     * **/
    public boolean checkCityCost() {
        return resources.hasResource(ResourceType.WHEAT, 2) && resources.hasResource(ResourceType.ORE, 3);
    }

    /**
     *check if we have more than 7 cards
     * @return boolean
     */
    public boolean isSevenCards() {
        return resources.totalCards()>7;
    }

    /**
     *add points to player
     * @param points
     */
    public void addPoints(int points) {
        this.totalPoints += points;
    }

    /**
     * checks valid position for placement for settlement
     * @param isInitialPlacement
     * @param map
     * @return int
     * **/
    protected int settlementLocation(GameMap map, boolean isInitialPlacement) {
        List<Integer> validNodes = new ArrayList<>();

        //loop through nodes
        for (int i = 0; i < 54; i++) {
            Node node = map.getNode(i);
            if (node == null || node.isOccupied()) continue;
            if(!map.isValidSettlementPosition(i)) {
                continue;
            }
            if(!isInitialPlacement && !map.hasAdjacentRoad(this,i)){
                continue;
            }
            validNodes.add(i);
        }

        if(validNodes.isEmpty()) {
            return -1;
        }

        return validNodes.get(random.nextInt(validNodes.size()));
    }

    /**
     * checks valid position for placement for road
     * @param map
     * @return int
     * **/
    protected int roadLocation(GameMap map){
        ArrayList<Integer> validEdges = new ArrayList<>();

        //loop through edges
        for (int i = 0; i < 72; i++) {
            Edge edge = map.getEdge(i);
            if(edge == null || edge.isOccupied()) { continue;}
            if(!map.isConnectedToAgent(this, i)){continue;}
            validEdges.add(i);
        }

        if(validEdges.isEmpty()) {
            return -1;
        }

        return validEdges.get(random.nextInt(validEdges.size()));
    }

    /**
     * checks valid position for placement for city
     * @param map
     * @return int
     * **/
    protected int cityLocation(GameMap map) {
        List<Integer> valid = new ArrayList<>();

        //loop through nodes
        for (int i = 0; i < 54; i++) {
            if (map.isSettlement(this, i)) {
                valid.add(i);
            }
        }

        if (valid.isEmpty()) return -1;

        return valid.get(random.nextInt(valid.size()));
    }

    // is called when agent has more than 7 cards so they need to return half
    protected void loseHalf() {

        System.out.println("\nTotal agent resources: " + getResources().totalCards());
        int returned = 0;
        int half = resources.totalCards() / 2;
        ResourceType[] types = {ResourceType.WOOD, ResourceType.BRICK, ResourceType.SHEEP, ResourceType.ORE, ResourceType.WHEAT};

        while (returned < half) {
            // picks a random type and checks if the agent has that, if it does, remove it
            ResourceType type = types[random.nextInt(types.length)];
            if (resources.hasResource(type, 1)) {
                resources.remove(type, 1);
                returned++;
            }
        }
        System.out.println("New total agent resources: " + getResources().totalCards());
    }

    // agent can steal card from another player if they roll a 7 and place a robber on the tile with that agent
    protected void stealCard(Agent victim) {

        if (victim.getResources().totalCards() == 0) {
            return;
        }

        // picks a random resource card to steal from the agent
        ResourceType[] types = {ResourceType.WOOD, ResourceType.BRICK, ResourceType.SHEEP, ResourceType.ORE, ResourceType.WHEAT};

        ResourceType type;
        do {
            type = types[random.nextInt(types.length)];
        } while (!victim.getResources().hasResource(type, 1));

        System.out.println("Victim Resources: " + victim.getResources().toString());
        System.out.println("AgentRolled Resources: " + this.getResources().toString());
        victim.getResources().remove(type, 1);
        this.resources.add(type, 1);
        System.out.println("Victim New Resources: " + victim.getResources().toString());
        System.out.println("AgentRolled New Resources: " + this.getResources().toString());
    }

}
