// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package Catan_Part2;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

/**
 * Represents a player (Agent) in the Catan game.
 * Handles building roads, settlements, and cities.
 * handle the resources card that the agent has
 *
 * @author Zain Khalboos
 * Course: SFWRENG 2AA4
 * Date: 2026-02-13add
 */
public class ComputerAgent extends Agent{


    /**
     * Constructor for agent
     *
     * @param id
     * @param resources
     * @param points
     */
    public ComputerAgent(int id, Resources resources, int points) {
        super(id, resources, points);
    }

    @Override
    public void takeTurn(GameMap map, int round) {

    }
}
