// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package Catan_Part2;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

/**
 * Represents a player (Agent) in the Catan game.
 * Handles building roads, settlements, and cities.
 * handle the resources card that the agent has
 *
 * @author Zain Khalboos
 * Course: SFWRENG 2AA4
 * Date: 2026-02-13add
 */
public class ComputerAgent extends Agent{

    private final Random random = new Random();

    /**
     * Constructor for agent
     *
     * @param id
     * @param resources
     * @param points
     */
    public ComputerAgent(int id, Resources resources, int points) {
        super(id, resources, points);
    }



    @Override
    public void takeTurn(GameMap map, int round, int rollDice) {


        int tries=0; //tries to make loop finite
        do { //start with one turn initially
            tries++;
            if (tries > 50) return; // safety break
            boolean built = false;

            List<Integer> options = new ArrayList<>(); //list our options
            options.add(0);
            options.add(1);
            options.add(2);
            Collections.shuffle(options, random); //shuffling the cards

            //loop through the options
            for (int choice : options) {

                if (choice == 0){
                    built = tryBuildRoad(map);

                    if (built) {
                        System.out.println(round + " / " + getId() + ": Built road at edge " + getEdgeId());
                    }
                }
                else if ( choice == 1) {
                    built = tryBuildSettlement(map);

                    if (built) {
                        System.out.println(round + " / " + getId() + ": Built settlement at node " + getNodeId());
                    }
                }

                else {
                    built = tryBuildCity(map);

                    if (built) {
                        System.out.println(round + " / " + getId() + ": Upgraded to city at node " + getNodeId());
                    }
                }

                if (built) {
                    break;
                }
            }


            // If nothing worked, end the turn
            if (!built) {
                return;
            }

        }while (isSevenCards());


    }
}
