// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package Catan_Part1;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/************************************************************/
/**
 *
 */
public class Agent {
    /**
     *
     */
    private int id;
    /**
     *
     */
    private int totalPoints;
    /**
     *
     */
    private Resources resources;

    private int roadsRemaining = 15;
    private int settlementsRemaining = 5;
    private int citiesRemaining = 4;
    /**
     *
     * @param id
     * @param resources
     * @param points
     */
    public Agent(int id, Resources resources, int points) {
        this.id = id;
        this.resources = resources;
        this.totalPoints = points;
    }

    public Resources getResources() {
        return resources;
    }

    /**
     *
     * @return
     */
    public int getId() {
        return id;
    }


    /**
     *
     * @param map
     */
    public void takeTurn(GameMap map, int round) {
        Random random = new Random();
        int tries=0;
        do {
            tries++;
            if (tries > 50) return; // safety break
            boolean built = false;

            int choice = random.nextInt(3);
            switch (choice) {
                case 2: built = tryBuildRoad(map); break;
                case 1: built = tryBuildSettlement(map); break;
                case 0: built = tryBuildCity(map); break;
            }
            // If that random pick didn’t work, try the other options too
            if (!built) {
                built = tryBuildCity(map) || tryBuildSettlement(map) || tryBuildRoad(map);
            }

            // If nothing worked, end the turn
            if(!built){return;}

        }while (isSevenCards());

    }

    private boolean tryBuildRoad(GameMap map) {
        if (roadsRemaining <= 0) return false;
        if(!checkRoadCost()){return false;}

        int edgeId=roadLocation(map);
        if(edgeId==-1){return false;}

        if(map.placeRoad(this, edgeId)){
            buyRoad();
            roadsRemaining--;
            return true;
        }

        return false;
    }

    private boolean tryBuildSettlement(GameMap map){
        if (settlementsRemaining <= 0) return false;
        if(!checkSettlementCost()){return false;}

        int nodeId=settlementLocation(map, false);
        if(nodeId==-1){return false;}

        if(map.placeSettlement(this, nodeId, false)){
            buySettlement();
            settlementsRemaining--;
            return true;
        }

        return false;
    }

    private boolean tryBuildCity(GameMap map){
        if (citiesRemaining <= 0) return false;
        if(!checkCityCost()){return false;}

        int nodeId=cityLocation(map);
        if (nodeId == -1) return false;

        if(map.upgrade(this, nodeId)){
            buyCity();
            citiesRemaining--;
            settlementsRemaining++;
            return true;
        }

        return false;
    }

    public int getTotalPoints() {
        return totalPoints;
    }

    /**
     *
     *
     *
     * @return boolean
     */
    public void buyRoad() {
        resources.remove(ResourceType.WOOD, 1);
        resources.remove(ResourceType.BRICK, 1);
    }

    public boolean checkRoadCost() {
        if(resources.hasResource(ResourceType.WOOD, 1) && resources.hasResource(ResourceType.BRICK, 1)) {
            return true;
        }
        return false;
    }

    /**
     *
     *
     *
     * @return boolean
     */
    public void buySettlement() {
        // Cost: 1 wood, 1 brick, 1 wheat, 1 sheep
        resources.remove(ResourceType.WOOD, 1);
        resources.remove(ResourceType.BRICK, 1);
        resources.remove(ResourceType.WHEAT, 1);
        resources.remove(ResourceType.SHEEP, 1);

    }

    public boolean checkSettlementCost() {
        if(resources.hasResource(ResourceType.WOOD, 1)
                && resources.hasResource(ResourceType.BRICK, 1)
                && resources.hasResource(ResourceType.WHEAT, 1)
                && resources.hasResource(ResourceType.SHEEP, 1)) {
            return true;
        }
        return false;
    }

    /**
     *
     *
     *
     * @return boolean
     */
    public void buyCity() {
        // Cost: 2 wheat, 3 ore
        resources.remove(ResourceType.WHEAT, 2);
        resources.remove(ResourceType.ORE, 3);

    }

    public boolean checkCityCost() {
        if(resources.hasResource(ResourceType.WHEAT, 2) && resources.hasResource(ResourceType.ORE, 3)) {
            return true;
        }
        return false;
    }

    /**
     *
     * @return boolean
     */
    public boolean isSevenCards() {
        return resources.totalCards()>7;
    }

    /**
     *
     * @param points
     */
    public void addPoints(int points) {
        this.totalPoints += points;
    }

    public int settlementLocation(GameMap map, boolean isInitialPlacement) {
        List<Integer> validNodes = new ArrayList<>();

        for (int i = 0; i < 54; i++) {
            Node node = map.getNode(i);
            if (node == null || node.isOccupied()) continue;
            if(!map.isValidSettlementPosition(i)) {
                continue;
            }
            if(!isInitialPlacement && !map.hasAdjacentRoad(this,i)){
                continue;
            }
            validNodes.add(i);
        }

        if(validNodes.isEmpty()) {
            return -1;
        }

        Random random = new Random();
        return validNodes.get(random.nextInt(validNodes.size()));
    }

    public int roadLocation(GameMap map){
        ArrayList<Integer> validEdges = new ArrayList<>();

        for (int i = 0; i < 72; i++) {
            Edge edge = map.getEdge(i);
            if(edge == null || edge.isOccupied()) { continue;}
            if(!map.isConnectedToAgent(this, i)){continue;}
            validEdges.add(i);
        }

        if(validEdges.isEmpty()) {
            return -1;
        }

        Random random = new Random();
        return validEdges.get(random.nextInt(validEdges.size()));
    }

    private int cityLocation(GameMap map) {
        List<Integer> valid = new ArrayList<>();

        for (int i = 0; i < 54; i++) {
            if (map.isSettlement(this, i)) {
                valid.add(i);
            }
        }

        if (valid.isEmpty()) return -1;

        Random random = new Random();
        return valid.get(random.nextInt(valid.size()));
    }

}
