// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public class Agent {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private int points;
	/**
	 * 
	 */
	private Resources resources;
	/**
	 * 
	 */
	public GameMap gamemap;


	/**
	 * 
	 * @param id 
	 * @param resources 
	 * @param points 
	 */
	public void Agents(int id, Resources resources, int points) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getId() {
        return 0;
	}

	/**
	 * 
	 * @return 
	 */
	public int getPoints() {
        return 0;
	}

	/**
	 * 
	 * @param map 
	 */
	public void takeTurn(GameMap map) {
	}

	/**
	 * 
	 * @param edgeId 
	 * @param map 
	 * @return 
	 */
	public boolean buildRoad(int edgeId, GameMap map) {
        return true;
	}

	/**
	 * 
	 * @param nodeId 
	 * @param map 
	 * @return 
	 */
	public boolean buildSettlement(int nodeId, GameMap map) {
        return true;
	}

	/**
	 * 
	 * @param nodeId 
	 * @param map 
	 * @return 
	 */
	public boolean buildCity(int nodeId, GameMap map) {
        return true;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isSevenCards() {
        return true;
	}

	/**
	 * 
	 * @param points 
	 */
	public void addPoints(int points) {
	}
}
