// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
// package Catan_Part1;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/************************************************************/
/**
 *
 */
public class Agent {
    /**
     *
     */
    private int id;
    /**
     *
     */
    private int totalPoints;
    /**
     *
     */
    private Resources resources;

    /**
     *
     * @param id
     * @param resources
     * @param points
     */
    public Agent(int id, Resources resources, int points) {
        this.id = id;
        this.resources = resources;
        this.totalPoints = points;
    }

    public Resources getResources() {
        return resources;
    }

    /**
     *
     * @return
     */
    public int getId() {
        return id;
    }


    /**
     *
     * @param map
     */
    public void takeTurn(GameMap map, int round) {
        for(int i=0;i<54;i++ ){
            if(buildCity(map)){
                if(map.upgrade(this, i))
                    return;
            }
        }
        for(int i=0;i<54;i++ ){
            if(buildSettlement(map)){
                if(map.placeSettlement(this, i, false))
                    return;
            }
        }

        for(int i=0;i<72;i++ ){
            if(buildRoad(map)){
                if(map.placeRoad(this, i))
                    return;
            }
        }

    }

    public int getTotalPoints() {
        return totalPoints;
    }

    /**
     *
     *
     * @param map
     * @return boolean
     */
    public boolean buildRoad(GameMap map) {
        // Cost: 1 wood, 1 brick
        if(resources.hasResource(ResourceType.WOOD, 1) && resources.hasResource(ResourceType.BRICK, 1)) {
            resources.remove(ResourceType.WOOD, 1);
            resources.remove(ResourceType.BRICK, 1);
            return true;
        }
        return false;
    }

    /**
     *
     *
     * @param map
     * @return boolean
     */
    public boolean buildSettlement(GameMap map) {
        // Cost: 1 wood, 1 brick, 1 wheat, 1 sheep
        if(resources.hasResource(ResourceType.WOOD, 1)
                && resources.hasResource(ResourceType.BRICK, 1)
                && resources.hasResource(ResourceType.WHEAT, 1)
                && resources.hasResource(ResourceType.SHEEP, 1)) {
            resources.remove(ResourceType.WOOD, 1);
            resources.remove(ResourceType.BRICK, 1);
            resources.remove(ResourceType.WHEAT, 1);
            resources.remove(ResourceType.SHEEP, 1);
            return true;
        }
        return false;
    }

    /**
     *
     *
     * @param map
     * @return boolean
     */
    public boolean buildCity(GameMap map) {
        // Cost: 2 wheat, 3 ore
        if(resources.hasResource(ResourceType.WHEAT, 2) && resources.hasResource(ResourceType.ORE, 3)) {
            resources.remove(ResourceType.WHEAT, 2);
            resources.remove(ResourceType.ORE, 3);
            return true;
        }
        return false;
    }

    /**
     *
     * @return boolean
     */
    public boolean isSevenCards() {
        return resources.totalCards()>7;
    }

    /**
     *
     * @param points
     */
    public void addPoints(int points) {
        this.totalPoints += points;
    }

    public int settlementLocation(GameMap map, boolean isInitialPlacement) {
        List<Integer> validNodes = new ArrayList<>();

        for (int i = 0; i < 54; i++) {
            Node node = map.getNode(i);
            if (node == null || node.isOccupied()) continue;
            if(!map.isValidSettlementPosition(i)) {
                continue;
            }
            if(!isInitialPlacement && !map.hasAdjacentRoad(this,i)){
                continue;
            }
            validNodes.add(i);
        }

        if(validNodes.isEmpty()) {
            return -1;
        }

        Random random = new Random();
        return validNodes.get(random.nextInt(validNodes.size()));
    }

    public int roadLocation(GameMap map){
        ArrayList<Integer> validEdges = new ArrayList<>();

        for (int i = 0; i < 72; i++) {
            Edge edge = map.getEdge(i);
            if(edge == null || edge.isOccupied()) { continue;}
            if(!map.isConnectedToAgent(this, i)){continue;}
            validEdges.add(i);
        }

        if(validEdges.isEmpty()) {
            return -1;
        }

        Random random = new Random();
        return validEdges.get(random.nextInt(validEdges.size()));
    }
}
