// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public abstract class Building {
	/**
	 * 
	 */
	private Agent owner;
	/**
	 * 
	 */
	public Agent agent;

	/**
	 * 
	 * @param owner 
	 */
	public void Building(Agent owner) {
	}
}
