// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public abstract class Building {
	/**
	 * 
	 */
	private Agent owner;


	/**
	 * 
	 * @param owner 
	 */
	public void Building(Agent owner) {
        this.owner = owner;
	}

    public Agent getOwner() { return owner; }
}
