// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public class City extends Building {
	/**
	 * 
	 */
	private Agent owner;

    public City(Agent owner) {
        super();
    }


    public Agent getOwner() {
        return owner;
    }
}
