// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public class City extends Building {
	/**
	 * 
	 */
	private Agent owner;

	/**
	 * 
	 * @param owner 
	 */
	public void City(Agent owner) {
	}
}
