// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public class Demonstrator {
	/**
	 * 
	 * @param args 
	 */
	public static void main(String[] args) {
	}
}
