// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public class Demonstrator {
	/**
	 * 
	 * @param args 
	 */
	public static void main(String[] args) {
        // Step 1: Initialize the game board (R1.1)
        // Creates 19 tiles, 54 nodes, 72 edges and all adjacency relationships
        GameMap map = new GameMap();
        map.initboard();

        // Step 2: Create 4 randomly acting agents (R1.2)
        // Each agent starts with 0 points and empty resources
        Agent[] agents = new Agent[4];
        for (int i = 0; i < 4; i++) {
            agents[i] = new Agent(i + 1, new Resources(), 0);
        }

        // Step 3: Create the game
        Game game = new Game(map, agents, 1);

        // Step 4: Initial placement phase
        // Each agent places 2 settlements and 2 roads
        System.out.println("=== INITIAL PLACEMENT PHASE ===");
        game.initalRound();

        // Step 5: Run the main game
        // Each round: roll dice, distribute resources, agents take turns
        System.out.println("\n=== MAIN GAME PHASE ===");
        game.runGame();

        /* Step 6: Print final results
        System.out.println("\n=== GAME OVER ===");
        for (Agent agent : agents) {
            System.out.println("Player " + agent.getId() + ": " + agent.getTotalPoints() + " VPs");
        }*/

        System.out.println("\n=== GAME OVER ===");
        for (Agent agent : agents) {
            System.out.println("Player " + agent.getId()
                    + ": " + agent.getTotalPoints() + " VPs"
                    + " | Cards: " + agent.getResources().totalCards());
        }
	}
}
