// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Road road;
	/**
	 * 
	 */
	public Building building;

	/**
	 * 
	 * @return 
	 */
	public int getId() {
        return 0;
	}

	/**
	 * 
	 * @return 
	 */
	public Road getRoad() {
        return new Road();
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
        return true;
	}

	/**
	 * 
	 * @param id 
	 * @param road 
	 */
	public void Edge(int id, Road road) {
	}
}
