// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public class Edge {

	private int id;
	private Road road;
	/**
	 * 
	 */
	public Building building;

	/**
	 * 
	 * @return id of the edge
	 */
	public int getId() {
        return this.id;
	}

	/**
	 * 
	 * @return 
	 */
	public Road getRoad() {
        return this.road;
	}

    public void setRoad(Road road) {
        this.road = road;
    }

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
        if (this.road==null){
            return false;
        }
        else {
            return true;
        }

	}


	/**
	 * 
	 * @param id 
	 */
	public  Edge(int id) {
        this.id=id;
        this.road=null;
	}
}
