// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private GameMap map;
	/**
	 * 
	 */
	private Agent[] agents;
	/**
	 * 
	 */
	private int round;
	/**
	 * 
	 */
	public Agent[] agent;

	/**
	 * 
	 */
	public void runGame() {
	}

	/**
	 * 
	 */
	public void runRound() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isDone() {
        return true;
	}
}
