// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Building building;

	/**
	 * 
	 * @return 
	 */
	public int getId() {
        return 0;
	}

	/**
	 * 
	 * @return 
	 * @return 
	 */
	public void getBuilding() {

	}

	/**
	 * 
	 * @param b 
	 */
	public void setBuilding(Building b) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
        return true;
	}

	/**
	 * 
	 * @param id 
	 * @param building 
	 */
	public void Node(int id, Building building) {
	}
}
