// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private undef building;
	/**
	 * 
	 */
	public Building building;

	/**
	 * 
	 * @return 
	 */
	public int getId() {
	}

	/**
	 * 
	 * @return 
	 * @return 
	 */
	public void getBuilding() {
	}

	/**
	 * 
	 * @param b 
	 */
	public void setBuilding(Building b) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
	}

	/**
	 * 
	 * @param id 
	 * @param building 
	 */
	public void Node(int id, undef building) {
	}
}
