// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public class ResourceCount {
	/**
	 * 
	 */
	private Resource Type resource;
	/**
				 * 
				 */
				private int amount;

	/**
	 * 
	 * @param resource 
	 * @param amount 
	 */
	public void ResourceCount(Resource Type resource, int amount) {
	}
}
