// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public class Resources {
	/**
	 * 
	 */
	private ResourceCount[] resources;
	/**
				 * 
				 */
				public Resource Type
	resource type;

	/**
	 * 
	 * @param resources 
	 */
	public void Resources(ResourceCount resources) {
	}

	/**
	 * 
	 * @return 
	 */
	public int totalCards() {
	}

	/**
	 * 
	 * @param resource 
	 */
	public void add(ResourceCount resource) {
	}

	/**
	 * 
	 * @param resource 
	 */
	public void remove(ResourceCount resource) {
	}
}
