
// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/**
 * Resources is class where the resources card saved, we can add card, remove card
 * and check if player has resources
 *
 * @author Zain Khalboos
 * Course: SFWRENG 2AA4
 * Date: 2026-02-13
 */
import java.util.Map;
import java.util.HashMap;

/**
 *
 */
public class Resources {

    private Map<ResourceType, Integer> resources; //map of resources
    /**
     *
     */

    /**
     *Constructor to initialize map of resources where each recourse has count of 0
     */
    public Resources() {
        resources = new HashMap<>();
        for (ResourceType resourceType : ResourceType.values()) {
            if (resourceType == ResourceType.DESERT) {
                continue;
            }
            resources.put(resourceType, 0);
        }
    }

    /**
     *return how much card in total
     * @return int
     */
    public int totalCards() {
        int total = 0;
        for (int amount : resources.values()) {
            total = amount + total;
        }
        return total;
    }

    /**
     *add card to map
     * @param resourceType
     * @param amount
     */
    public void add(ResourceType resourceType, int amount) {
        if (resourceType != ResourceType.DESERT && amount > 0) {
            Integer oldAmount = resources.get(resourceType);
            resources.replace(resourceType, oldAmount + amount);
        }
    }

    /**
     *remove card from map
     * @param resourceType
     * @param amount
     */
    public boolean remove(ResourceType resourceType, int amount) {
        if (resourceType != ResourceType.DESERT && amount > 0) {
            Integer oldAmount = resources.get(resourceType);
            if (oldAmount - amount < 0) {
                return false;
            }
            resources.replace(resourceType, oldAmount - amount);
            return true;
        }

        return false;
    }

    /**
     *check if we have the needed resources
     * @param resourceType
     * @param needAmount
     */
    public boolean hasResource(ResourceType resourceType, int needAmount) {
        if(resourceType != ResourceType.DESERT && needAmount > 0){
            Integer Actulamount = resources.get(resourceType);
            if (Actulamount >= needAmount) {
                return true;
            }
        }
        return false;
    }
}
