// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/

import java.util.Map;
import java.util.HashMap;

/**
 * 
 */
public class Resources {

    private Map<ResourceType, Integer> resources;
    /**
     *
     */

    /**
     *
     *
     */
    public Resources() {
        resources = new HashMap<>();
        for (ResourceType resourceType : ResourceType.values()) {
            if (resourceType == ResourceType.DESERT) {
                continue;
            }
            resources.put(resourceType, 0);
        }
    }

    /**
     *
     * @return int
     */
    public int totalCards() {
        int total = 0;
        for (int amount : resources.values()) {
            total = amount + total;
        }
        return total;
    }

    /**
     *
     * @param resourceType
     * @param amount
     */
    public void add(ResourceType resourceType, int amount) {
        if (resourceType != ResourceType.DESERT && amount > 0) {
            Integer oldAmount = resources.get(resourceType);
            resources.replace(resourceType, oldAmount + amount);
        }
    }

    /**
     *
     * @param resourceType
     * @param amount
     */
    public boolean remove(ResourceType resourceType, int amount) {
        if (resourceType != ResourceType.DESERT && amount > 0) {
            Integer oldAmount = resources.get(resourceType);
            if (oldAmount - amount < 0) {
                return false;
            }
            resources.replace(resourceType, oldAmount - amount);
            return true;
        }

        return false;
    }

    public boolean hasResource(ResourceType resourceType, int needAmount) {
        if(resourceType != ResourceType.DESERT && needAmount > 0){
            Integer Actulamount = resources.get(resourceType);
            if (Actulamount >= needAmount) {
                return true;
            }
        }
        return false;
    }
}
