// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public class Road extends Building {
	/**
	 * 
	 */
	private Agent owner;



    /**
	 * 
	 * @param owner 
	 */
	public Road(Agent owner) {
        this.owner = owner;
	}

    public Agent getOwner() {
        return owner;
    }

}
