// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public class Settlement extends Building {
	/**
	 * 
	 */
	private Agent owner;

    public Settlement(Agent owner) {
        super();
    }



    public Agent getOwner() {
        return owner;
    }
}
