// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Part1;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private ResourceType resourceType;
	/**
	 * 
	 */
	private int numToken;
	/**
	 * 
	 */
	public Resources resources;

	/**
	 * 
	 * @return 
	 */
	public void getResourceType() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getNumberToken() {
        return 0;
	}

	/**
	 * 
	 * @param id 
	 * @param building 
	 */
	public void Tile(int id, Building building) {
	}
}
